# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19b1b6c3634e3b7a921ee902a4b042cb662b75fcf4d6c9e2959f16c57c3fe4f98c174d563325369af8b0f9639542c6dd19358c6e1c324ab794b699e4340a7b68

test:
  secret_key_base: ad037dd4c1cecfa1641e6af4584cae27094d748d81e7ba6ba7722579d4c55e3d00d77bb4430c31e12ef67db8802ab96b2b0f068bbf0ea543205598f45b04e8ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
